name: oh_my_cat
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  #sdk: ">=2.18.0 <4.0.0"
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  formz: ^0.4.1
  http: ^0.13.5
  intl: ^0.17.0

dev_dependencies:
  alchemist: ^0.5.1
  bloc_test: ^9.1.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.12
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  patrol: ^0.7.2
  very_good_analysis: ^3.1.0



flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/cat.png"

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: assets/cat.png